<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <services>
        <service id="fos_rest.exception_listener" class="FOS\RestBundle\EventListener\ExceptionListener">
            <tag name="monolog.logger" channel="request" />
            <argument type="service" id="security.token_storage" />
            <argument type="service" id="security.authentication.trust_resolver" />
            <argument type="service" id="security.http_utils" />
            <argument />
            <argument type="service" id="security.authentication.entry_point" on-invalid="null" />
            <argument>%security.access.denied_url%</argument>
            <argument type="service" id="security.access.denied_handler" on-invalid="null" />
            <argument type="service" id="logger" on-invalid="null" />
            <argument>false</argument> <!-- Stateless -->
            <argument>fos_rest.exception.controller:showAction</argument>
        </service>

        <service id="security.exception_listener" alias="fos_rest.exception_listener" />
        <!-- for Symfony 2.8 compatibility - otherwise they are not able to reference security.exception_listener -->
        <service id="security.exception_listener.main" alias="fos_rest.exception_listener" />
        <service id="security.exception_listener.default" alias="fos_rest.exception_listener" />

        <service id="fos_rest.exception.controller" class="FOS\RestBundle\Controller\ExceptionController">
            <argument type="service" id="fos_rest.view_handler" />
            <argument type="service" id="fos_rest.exception.codes_map" />  <!-- exception codes -->
            <argument /><!-- show exception -->
        </service>

        <service id="fos_rest.exception.twig_controller" class="FOS\RestBundle\Controller\TwigExceptionController" parent="fos_rest.exception.controller">
            <argument type="service" id="templating.engine.twig" />
        </service>

        <service id="fos_rest.exception.codes_map" class="FOS\RestBundle\Util\ExceptionValueMap" public="false">
            <argument type="collection"/> <!-- exception codes -->
        </service>

        <service id="fos_rest.exception.messages_map" class="FOS\RestBundle\Util\ExceptionValueMap" public="false">
            <argument type="collection"/> <!-- exception messages -->
        </service>

        <service id="fos_rest.serializer.exception_normalizer.jms" class="FOS\RestBundle\Serializer\Normalizer\ExceptionHandler">
            <argument type="service" id="fos_rest.exception.messages_map" /> <!-- exception messages -->
            <argument /><!-- show exception message -->
            <tag name="jms_serializer.subscribing_handler" />
        </service>

        <service id="fos_rest.serializer.exception_normalizer.symfony" class="FOS\RestBundle\Serializer\Normalizer\ExceptionNormalizer" public="false">
            <argument type="service" id="fos_rest.exception.messages_map" /> <!-- exception messages -->
            <argument /><!-- show exception message -->
            <tag name="serializer.normalizer" priority="-10" />
        </service>
    </services>
</container>
